/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './home.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/router/src/router_module';
import * as import4 from '@angular/forms/src/directives';
import * as import5 from '@angular/forms/src/form_providers';
import * as import6 from '../shared/shared.module';
import * as import7 from './home-routing.module';
import * as import8 from '../+swiper/swiper.module';
import * as import9 from '../shared/lazyload-image/lazyload-image.module';
import * as import10 from '../shared/widgets/widgets.module';
import * as import11 from '@angular/common/src/localization';
import * as import12 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import13 from '@angular/forms/src/form_builder';
import * as import14 from '@angular/core/src/di/injector';
import * as import15 from './home.component.ngfactory';
import * as import16 from '../shared/widgets/mega-menu/mega-menu.component.ngfactory';
import * as import17 from '../shared/widgets/mega-menu/mega-menu-link.component.ngfactory';
import * as import18 from '../shared/widgets/announcement-widget/announcement-widget.component.ngfactory';
import * as import19 from '../shared/widgets/category-widget/category-widget.component.ngfactory';
import * as import20 from '../shared/widgets/extra-menu/extra-menu.component.ngfactory';
import * as import21 from '../shared/widgets/hero-banner/hero-banner.component.ngfactory';
import * as import22 from '../shared/widgets/portfolio-widget/portfolio-widget.component.ngfactory';
import * as import23 from '../shared/widgets/storyline-widget/storyline-widget.component.ngfactory';
import * as import24 from '../shared/widgets/product-slider/product-slider.component.ngfactory';
import * as import25 from '../shared/widgets/testimonials-widget/testimonials-widget.component.ngfactory';
import * as import26 from '../shared/widgets/pagination/pagination.component.ngfactory';
import * as import27 from '../shared/widgets/product-card/product-card.component.ngfactory';
import * as import28 from '@angular/core/src/i18n/tokens';
import * as import29 from './home.component';
import * as import30 from '@angular/router/src/router_config_loader';
class HomeModuleInjector extends import0.NgModuleInjector<import1.HomeModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _InternalFormsSharedModule_2:import4.InternalFormsSharedModule;
  _FormsModule_3:import5.FormsModule;
  _ReactiveFormsModule_4:import5.ReactiveFormsModule;
  _SharedModule_5:import6.SharedModule;
  _HomeRoutingModule_6:import7.HomeRoutingModule;
  _SwiperModule_7:import8.SwiperModule;
  _LazyLoadImageModule_8:import9.LazyLoadImageModule;
  _WidgetModule_9:import10.WidgetModule;
  _HomeModule_10:import1.HomeModule;
  __NgLocalization_11:import11.NgLocaleLocalization;
  __RadioControlRegistry_12:import12.RadioControlRegistry;
  __FormBuilder_13:import13.FormBuilder;
  __ROUTES_14:any[];
  constructor(parent:import14.Injector) {
    super(parent,[
      import15.HomeComponentNgFactory,
      import16.MegaMenuComponentNgFactory,
      import17.MegaMenuLinkComponentNgFactory,
      import18.AnnouncementWidgetComponentNgFactory,
      import19.CategoryWidgetComponentNgFactory,
      import20.ExtraMenuComponentNgFactory,
      import21.HeroBannerComponentNgFactory,
      import22.PortfolioWidgetComponentNgFactory,
      import23.StorylineWidgetComponentNgFactory,
      import24.ProductSliderComponentNgFactory,
      import25.TestimonialsWidgetComponentNgFactory,
      import26.PaginationComponentNgFactory,
      import27.ProductCardComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_11():import11.NgLocaleLocalization {
    if ((this.__NgLocalization_11 == (null as any))) { (this.__NgLocalization_11 = new import11.NgLocaleLocalization(this.parent.get(import28.LOCALE_ID))); }
    return this.__NgLocalization_11;
  }
  get _RadioControlRegistry_12():import12.RadioControlRegistry {
    if ((this.__RadioControlRegistry_12 == (null as any))) { (this.__RadioControlRegistry_12 = new import12.RadioControlRegistry()); }
    return this.__RadioControlRegistry_12;
  }
  get _FormBuilder_13():import13.FormBuilder {
    if ((this.__FormBuilder_13 == (null as any))) { (this.__FormBuilder_13 = new import13.FormBuilder()); }
    return this.__FormBuilder_13;
  }
  get _ROUTES_14():any[] {
        if ((this.__ROUTES_14 == (null as any))) { (this.__ROUTES_14 = [[{
          path: '',
          component: import29.HomeComponent
        }
    ]]); }
    return this.__ROUTES_14;
  }
  createInternal():import1.HomeModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ROUTER_FORROOT_GUARD,(null as any)));
    this._InternalFormsSharedModule_2 = new import4.InternalFormsSharedModule();
    this._FormsModule_3 = new import5.FormsModule();
    this._ReactiveFormsModule_4 = new import5.ReactiveFormsModule();
    this._SharedModule_5 = new import6.SharedModule();
    this._HomeRoutingModule_6 = new import7.HomeRoutingModule();
    this._SwiperModule_7 = new import8.SwiperModule();
    this._LazyLoadImageModule_8 = new import9.LazyLoadImageModule();
    this._WidgetModule_9 = new import10.WidgetModule();
    this._HomeModule_10 = new import1.HomeModule();
    return this._HomeModule_10;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import4.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_2; }
    if ((token === import5.FormsModule)) { return this._FormsModule_3; }
    if ((token === import5.ReactiveFormsModule)) { return this._ReactiveFormsModule_4; }
    if ((token === import6.SharedModule)) { return this._SharedModule_5; }
    if ((token === import7.HomeRoutingModule)) { return this._HomeRoutingModule_6; }
    if ((token === import8.SwiperModule)) { return this._SwiperModule_7; }
    if ((token === import9.LazyLoadImageModule)) { return this._LazyLoadImageModule_8; }
    if ((token === import10.WidgetModule)) { return this._WidgetModule_9; }
    if ((token === import1.HomeModule)) { return this._HomeModule_10; }
    if ((token === import11.NgLocalization)) { return this._NgLocalization_11; }
    if ((token === import12.RadioControlRegistry)) { return this._RadioControlRegistry_12; }
    if ((token === import13.FormBuilder)) { return this._FormBuilder_13; }
    if ((token === import30.ROUTES)) { return this._ROUTES_14; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const HomeModuleNgFactory:import0.NgModuleFactory<import1.HomeModule> = new import0.NgModuleFactory(HomeModuleInjector,import1.HomeModule);