/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.listing-container[_ngcontent-%COMP%]   .filter[_ngcontent-%COMP%] {\n  z-index: 102;\n  overflow-y: scroll;\n}\n\n.sort-listing-content[_ngcontent-%COMP%] {\n  list-style: none;\n  padding-left: 0px;\n  margin-bottom: 0px;\n}\n\n.close[_ngcontent-%COMP%] {\n  font-size: 18px;\n  line-height: 22px;\n  color: #fff;\n  opacity: 1;\n}\n\n.clear-all[_ngcontent-%COMP%]   .close[_ngcontent-%COMP%] {\n  color: black;\n}\nimg.right-filter-ico[_ngcontent-%COMP%] {\n  width: 25px;\n  transform: rotate(180deg);\n  -moz-transform: rotate(180deg);\n  -o-transform: rotate(180deg);\n  -ms-transform: rotate(180deg);\n  -webkit-transform: rotate(180deg);\n  margin: 5px;\n}\nimg.filter-ico[_ngcontent-%COMP%] {\n    width: 18px;\n}\nimg.sort-ico[_ngcontent-%COMP%] {\n    width: 20px;\n}'];