/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.contact-form[_ngcontent-%COMP%]{\n	float: none !important;\n	margin: 0 auto;\n}\n.form-submit-btn[_ngcontent-%COMP%]{\n	background-color: #981937;\n	border: 2px solid #981937;\n}\n.form-submit-btn[_ngcontent-%COMP%]:hover{\n    background-color: #FFF;\n    color: #981937;\n}\n.form-submit-btn.disabled[_ngcontent-%COMP%]{\n	pointer-events: none;\n	cursor: default;\n}\n.form-submit-msg[_ngcontent-%COMP%]{\n	margin-top: 15px;\n}'];