/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from './shared/services/http-client.service';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from './app.component.css.shim';
import * as import14 from './shared/services/cart-details.service';
import * as import15 from './shared/widgets/header/header.component.ngfactory';
import * as import16 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import17 from './shared/widgets/footer/footer.component.ngfactory';
import * as import18 from '@angular/core/src/linker/component_factory_resolver';
import * as import19 from './shared/widgets/mega-menu/mega-menu.component.ngfactory';
import * as import20 from '@angular/router/src/router_outlet_map';
import * as import21 from '@angular/core/src/linker/component_factory_resolver';
import * as import22 from './shared/widgets/header/header.component';
import * as import23 from '@angular/router/src/directives/router_outlet';
import * as import24 from './shared/widgets/footer/footer.component';
export class Wrapper_AppComponent {
  context:import0.AppComponent;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.AppComponent(p0,p1);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _HttpClientService_0_4:import4.HttpClientService;
  _AppComponent_0_5:Wrapper_AppComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import5.selectOrCreateRenderHostElement(this.renderer,'cvi-root',import5.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HttpClientService_0_4 = new import4.HttpClientService(this.parentInjector.get(import9.Http));
    this._AppComponent_0_5 = new Wrapper_AppComponent(this.parentInjector.get(import10.Router),this._HttpClientService_0_4);
    this._appEl_0.initComponent(this._AppComponent_0_5.context,([] as any[]),compView_0);
    compView_0.create(this._AppComponent_0_5.context,this.projectableNodes,(null as any));
    var disposable_0:Function = this.renderer.listenGlobal('window','scroll',this.eventHandler(this._handle_scroll_0_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],[disposable_0],([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.HttpClientService) && (0 === requestNodeIndex))) { return this._HttpClientService_0_4; }
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_5.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._AppComponent_0_5.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_scroll_0_0($event:any):boolean {
    this._appEl_0.componentView.markPathToRootAsCheckOnce();
    const pd_0_0:any = ((<any>this._AppComponent_0_5.context.showMegaMenu($event)) !== false);
    return (true && pd_0_0);
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import12.ComponentFactory<import0.AppComponent> = new import12.ComponentFactory<import0.AppComponent>('cvi-root',viewFactory_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = [import13.styles];
var renderType_AppComponent:import2.RenderComponentType = (null as any);
class _View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ComponentFactoryResolver_0_4:any;
  _CartDetailsService_0_5:import14.CartDetailsService;
  _HeaderComponent_0_6:import15.Wrapper_HeaderComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _RouterOutlet_4_5:import16.Wrapper_RouterOutlet;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _FooterComponent_7_4:import17.Wrapper_FooterComponent;
  _text_8:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import5.createRenderElement(this.renderer,parentRenderNode,'cvi-header',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import15.viewFactory_HeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ComponentFactoryResolver_0_4 = new import18.CodegenComponentFactoryResolver([import19.MegaMenuComponentNgFactory],this.parentInjector.get(import18.ComponentFactoryResolver));
    this._CartDetailsService_0_5 = new import14.CartDetailsService(this.parentInjector.get(import4.HttpClientService));
    this._HeaderComponent_0_6 = new import15.Wrapper_HeaderComponent(this.parentInjector.get(import10.Router),this._ComponentFactoryResolver_0_4,this._CartDetailsService_0_5);
    this._appEl_0.initComponent(this._HeaderComponent_0_6.context,([] as any[]),compView_0);
    compView_0.create(this._HeaderComponent_0_6.context,([] as any[]),(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = import5.createRenderElement(this.renderer,parentRenderNode,'div',new import5.InlineArray2(2,'class','cvi-outlet-body'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._el_4 = import5.createRenderElement(this.renderer,this._el_2,'router-outlet',new import5.InlineArray2(2,'routing-helper',''),(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    this._RouterOutlet_4_5 = new import16.Wrapper_RouterOutlet(this.parentInjector.get(import20.RouterOutletMap),this._appEl_4.vcRef,this.parentInjector.get(import21.ComponentFactoryResolver),(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n',(null as any));
    this._text_6 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_7 = import5.createRenderElement(this.renderer,parentRenderNode,'cvi-footer',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_7 = new import3.AppElement(7,(null as any),this,this._el_7);
    var compView_7:any = import17.viewFactory_FooterComponent0(this.viewUtils,this.injector(7),this._appEl_7);
    this._FooterComponent_7_4 = new import17.Wrapper_FooterComponent();
    this._appEl_7.initComponent(this._FooterComponent_7_4.context,([] as any[]),compView_7);
    compView_7.create(this._FooterComponent_7_4.context,([] as any[]),(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listenGlobal('window','scroll',this.eventHandler(this._handle_scroll_0_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.ComponentFactoryResolver) && (0 === requestNodeIndex))) { return this._ComponentFactoryResolver_0_4; }
    if (((token === import14.CartDetailsService) && (0 === requestNodeIndex))) { return this._CartDetailsService_0_5; }
    if (((token === import22.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_6.context; }
    if (((token === import23.RouterOutlet) && (4 === requestNodeIndex))) { return this._RouterOutlet_4_5.context; }
    if (((token === import24.FooterComponent) && (7 === requestNodeIndex))) { return this._FooterComponent_7_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.hasMegaMenu;
    this._HeaderComponent_0_6.check_showMegaMenuCaret(currVal_0_0_0,throwOnChange,false);
    this._HeaderComponent_0_6.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this._RouterOutlet_4_5.detectChangesInInputProps(this,this._el_4,throwOnChange);
    this._FooterComponent_7_4.detectChangesInInputProps(this,this._el_7,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._HeaderComponent_0_6.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this._RouterOutlet_4_5.detectChangesInHostProps(this,this._el_4,throwOnChange);
    this._FooterComponent_7_4.detectChangesInHostProps(this,this._el_7,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterOutlet_4_5.context.ngOnDestroy();
  }
  private _handle_scroll_0_0($event:any):boolean {
    this._appEl_0.componentView.markPathToRootAsCheckOnce();
    const pd_0_0:any = ((<any>this._HeaderComponent_0_6.context.hideMegaMenuOnScroll($event)) !== false);
    return (true && pd_0_0);
  }
}
export function viewFactory_AppComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.Emulated,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}