/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './statics-routing.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/core/src/di/injector';
import * as import4 from './about-us/about-us.component.ngfactory';
import * as import5 from './faqs/faqs.component.ngfactory';
import * as import6 from './order-tracking/order-tracking.component.ngfactory';
import * as import7 from './in-media/in-media.component.ngfactory';
import * as import8 from './contact-us/contactus.component.ngfactory';
import * as import9 from './terms-and-condition/terms-condition.component.ngfactory';
import * as import10 from './shipping-refunds/shipping-refund.component.ngfactory';
import * as import11 from './about-us/about-us.component';
import * as import12 from './faqs/faqs.component';
import * as import13 from './order-tracking/order-tracking.component';
import * as import14 from './in-media/in-media.component';
import * as import15 from './contact-us/contactus.component';
import * as import16 from './terms-and-condition/terms-condition.component';
import * as import17 from './shipping-refunds/shipping-refund.component';
import * as import18 from '@angular/router/src/router_config_loader';
class StaticsRoutingModuleInjector extends import0.NgModuleInjector<import1.StaticsRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _StaticsRoutingModule_1:import1.StaticsRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import3.Injector) {
    super(parent,[
      import4.AboutUsComponentNgFactory,
      import5.FaqsComponentNgFactory,
      import6.OrderTrackingComponentNgFactory,
      import7.InMediaComponentNgFactory,
      import8.ContactUsComponentNgFactory,
      import9.TermsConditionComponentNgFactory,
      import10.ShippingRefundComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _ROUTES_2():any[] {
      if ((this.__ROUTES_2 == (null as any))) { (this.__ROUTES_2 = [[
        {
          path: 'about_us',
          component: import11.AboutUsComponent
        }
        ,
        {
          path: 'faqs',
          component: import12.FaqsComponent
        }
        ,
        {
          path: 'order_tracking',
          component: import13.OrderTrackingComponent
        }
        ,
        {
          path: 'craftsvilla_in_media',
          component: import14.InMediaComponent
        }
        ,
        {
          path: 'contactus',
          component: import15.ContactUsComponent
        }
        ,
        {
          path: 'terms-and-conditions',
          component: import16.TermsConditionComponent
        }
        ,
        {
          path: 'shipping-and-refunds',
          component: import17.ShippingRefundComponent
        }

      ]
    ]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.StaticsRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ROUTER_FORROOT_GUARD,(null as any)));
    this._StaticsRoutingModule_1 = new import1.StaticsRoutingModule();
    return this._StaticsRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.StaticsRoutingModule)) { return this._StaticsRoutingModule_1; }
    if ((token === import18.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const StaticsRoutingModuleNgFactory:import0.NgModuleFactory<import1.StaticsRoutingModule> = new import0.NgModuleFactory(StaticsRoutingModuleInjector,import1.StaticsRoutingModule);