/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../../app/shared/services/http-client.service';
import * as import4 from '../../../../../app/shared/widgets/product-slider/product-slider.component';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from './product-slider.component.css.shim';
import * as import13 from '@angular/common/src/directives/ng_for';
import * as import14 from '@angular/common/src/pipes/number_pipe';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '@angular/core/src/i18n/tokens';
import * as import18 from '@angular/core/src/security';
import * as import19 from '@angular/router/src/directives/router_link';
import * as import20 from '@angular/router/src/router';
import * as import21 from '@angular/router/src/router_state';
import * as import22 from '@angular/common/src/location/location_strategy';
var renderType_ProductSliderComponent_Host:import0.RenderComponentType = (null as any);
class _View_ProductSliderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HttpClientService_0_4:import3.HttpClientService;
  _ProductSliderComponent_0_5:import4.ProductSliderComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ProductSliderComponent_Host0,renderType_ProductSliderComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('cvi-product-slider',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ProductSliderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HttpClientService_0_4 = new import3.HttpClientService(this.parentInjector.get(import9.Http));
    this._ProductSliderComponent_0_5 = new import4.ProductSliderComponent(this._HttpClientService_0_4);
    this._appEl_0.initComponent(this._ProductSliderComponent_0_5,[],compView_0);
    compView_0.create(this._ProductSliderComponent_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HttpClientService) && (0 === requestNodeIndex))) { return this._HttpClientService_0_4; }
    if (((token === import4.ProductSliderComponent) && (0 === requestNodeIndex))) { return this._ProductSliderComponent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ProductSliderComponent_0_5.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ProductSliderComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ProductSliderComponent_Host === (null as any))) { (renderType_ProductSliderComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_ProductSliderComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ProductSliderComponentNgFactory:import11.ComponentFactory<import4.ProductSliderComponent> = new import11.ComponentFactory<import4.ProductSliderComponent>('cvi-product-slider',viewFactory_ProductSliderComponent_Host0,import4.ProductSliderComponent);
const styles_ProductSliderComponent:any[] = [import12.styles];
var renderType_ProductSliderComponent:import0.RenderComponentType = (null as any);
class _View_ProductSliderComponent0 extends import1.AppView<import4.ProductSliderComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _TemplateRef_22_5:any;
  _NgFor_22_6:import13.NgFor;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _TemplateRef_28_5:any;
  _NgFor_28_6:import13.NgFor;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  _pipe_number_0:import14.DecimalPipe;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ProductSliderComponent0,renderType_ProductSliderComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','occupy mob-section');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','contain bg-white mob-bg-white home-section home-listing clearfix');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','section-header mob-section-heading');
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'span',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','heading pull-left');
    this._el_7 = this.renderer.createElement(this._el_6,'img',(null as any));
    this.renderer.setElementAttribute(this._el_7,'src','../../../../images//ethnic-1.png');
    this._text_8 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_4,'button',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','btn btn-brand btn-xs view-more pull-right');
    this._text_11 = this.renderer.createText(this._el_10,'View more',(null as any));
    this._text_12 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','section-body text-center page-listing');
    this._text_15 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','col-md-12');
    this._text_17 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','carousel slide');
    this._text_19 = this.renderer.createText(this._el_18,'\n          ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'ol',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','carousel-indicators');
    this._text_21 = this.renderer.createText(this._el_20,'\n            ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_20,(null as any));
    this._appEl_22 = new import2.AppElement(22,20,this,this._anchor_22);
    this._TemplateRef_22_5 = new import15.TemplateRef_(this._appEl_22,viewFactory_ProductSliderComponent1);
    this._NgFor_22_6 = new import13.NgFor(this._appEl_22.vcRef,this._TemplateRef_22_5,this.parentInjector.get(import16.IterableDiffers),this.ref);
    this._text_23 = this.renderer.createText(this._el_20,'\n          ',(null as any));
    this._text_24 = this.renderer.createText(this._el_18,'\n          ',(null as any));
    this._text_25 = this.renderer.createText(this._el_18,'\n          ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_18,'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','carousel-inner');
    this._text_27 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_26,(null as any));
    this._appEl_28 = new import2.AppElement(28,26,this,this._anchor_28);
    this._TemplateRef_28_5 = new import15.TemplateRef_(this._appEl_28,viewFactory_ProductSliderComponent2);
    this._NgFor_28_6 = new import13.NgFor(this._appEl_28.vcRef,this._TemplateRef_28_5,this.parentInjector.get(import16.IterableDiffers),this.ref);
    this._text_29 = this.renderer.createText(this._el_26,'\n          ',(null as any));
    this._text_30 = this.renderer.createText(this._el_18,'\n          ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_18,'a',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','left carousel-control product-slider-prev');
    this.renderer.setElementAttribute(this._el_31,'data-slide','prev');
    this._text_32 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'img',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','pull-left listing-arrow hide-sm');
    this.renderer.setElementAttribute(this._el_33,'src','../../../../images//left-arrow.png');
    this._text_34 = this.renderer.createText(this._el_31,'\n          ',(null as any));
    this._text_35 = this.renderer.createText(this._el_18,'\n          ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_18,'a',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','right carousel-control product-slider-next');
    this.renderer.setElementAttribute(this._el_36,'data-slide','next');
    this._text_37 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'img',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','pull-right listing-arrow hide-sm');
    this.renderer.setElementAttribute(this._el_38,'src','../../../../images//right-arrow.png');
    this._text_39 = this.renderer.createText(this._el_36,'\n          ',(null as any));
    this._text_40 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._text_41 = this.renderer.createText(this._el_16,'\n      ',(null as any));
    this._text_42 = this.renderer.createText(this._el_14,'\n    ',(null as any));
    this._text_43 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_44 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_45 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._pipe_number_0 = new import14.DecimalPipe(this.parentInjector.get(import17.LOCALE_ID));
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import13.NgFor) && (22 === requestNodeIndex))) { return this._NgFor_22_6; }
    if (((token === import15.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import13.NgFor) && (28 === requestNodeIndex))) { return this._NgFor_28_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_2:any = this.context.dataItems;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgFor_22_6.ngForOf = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._NgFor_22_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_22_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_3:any = this.context.productDblArray;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgFor_28_6.ngForOf = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgFor_28_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_28_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import5.interpolate(1,' ',this.context.header,'');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_8,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.getSliderId();
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementAttribute(this._el_18,'id',((currVal_1 == (null as any))? (null as any): currVal_1.toString()));
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this.context.getIdTarget();
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_31,'href',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_4));
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.getIdTarget();
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_36,'href',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ProductSliderComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.ProductSliderComponent> {
  if ((renderType_ProductSliderComponent === (null as any))) { (renderType_ProductSliderComponent = viewUtils.createRenderComponentType('/home/craftsvilla/angular2-aot-webpack2-rollup/app/shared/widgets/product-slider/product-slider.component.html',0,import10.ViewEncapsulation.Emulated,styles_ProductSliderComponent,{})); }
  return new _View_ProductSliderComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ProductSliderComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ProductSliderComponent1,renderType_ProductSliderComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.getIdTarget();
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementAttribute(this._el_0,'data-target',((currVal_0 == (null as any))? (null as any): currVal_0.toString()));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.index;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementAttribute(this._el_0,'data-slide-to',((currVal_1 == (null as any))? (null as any): currVal_1.toString()));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = (this.context.index == 0);
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_0,'active',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ProductSliderComponent1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ProductSliderComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ProductSliderComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import13.NgFor;
  _text_3:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ProductSliderComponent2,renderType_ProductSliderComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item');
    this._text_1 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import15.TemplateRef_(this._appEl_2,viewFactory_ProductSliderComponent3);
    this._NgFor_2_6 = new import13.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import16.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import13.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this.context.$implicit;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgFor_2_6.ngForOf = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = (this.context.index == 0);
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'active',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ProductSliderComponent2(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ProductSliderComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_ProductSliderComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _RouterLinkWithHref_3_3:import19.RouterLinkWithHref;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  _pipe_number_0_0:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ProductSliderComponent3,renderType_ProductSliderComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','product-listing col-sm-3 col-xs-6');
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._RouterLinkWithHref_3_3 = new import19.RouterLinkWithHref(this.parent.parent.parentInjector.get(import20.Router),this.parent.parent.parentInjector.get(import21.ActivatedRoute),this.parent.parent.parentInjector.get(import22.LocationStrategy));
    this._text_4 = this.renderer.createText(this._el_3,'\n                  ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'img',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','img-responsive');
    this._text_6 = this.renderer.createText(this._el_3,'\n                  ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','product-info');
    this._text_8 = this.renderer.createText(this._el_7,'\n                    ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','product-name');
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n                    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','product-price');
    this._text_13 = this.renderer.createText(this._el_12,'\n                      ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'span',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','discounted-price');
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n                       ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_12,'span',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','actual-price');
    this._el_18 = this.renderer.createElement(this._el_17,'s',(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'',(null as any));
    this._text_20 = this.renderer.createText(this._el_12,'\n                       ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_12,'span',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','discount');
    this._text_22 = this.renderer.createText(this._el_21,'',(null as any));
    this._text_23 = this.renderer.createText(this._el_12,'\n                    ',(null as any));
    this._text_24 = this.renderer.createText(this._el_7,'\n                  ',(null as any));
    this._text_25 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_3,'click',this.eventHandler(this._handle_click_3_0.bind(this)));
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._pipe_number_0_0 = import5.pureProxy2((<_View_ProductSliderComponent0>this.parent.parent)._pipe_number_0.transform.bind((<_View_ProductSliderComponent0>this.parent.parent)._pipe_number_0));
    this._expr_8 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.RouterLinkWithHref) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._RouterLinkWithHref_3_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    const valUnwrapper:any = new import8.ValueUnwrapper();
    changes = (null as any);
    const currVal_2:any = import5.interpolate(1,'/product/',this.context.$implicit.productId,'');
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._RouterLinkWithHref_3_3.routerLink = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_3_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._RouterLinkWithHref_3_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_3,'href',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.$implicit.imgUrl;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_5,'src',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_4));
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import5.interpolate(1,'',this.context.$implicit.productName,'');
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_10,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import5.interpolate(1,'$',this.context.$implicit.discountedPrice,'');
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_15,currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import5.interpolate(1,'$',this.context.$implicit.regularPrice,'');
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_19,currVal_7);
      this._expr_7 = currVal_7;
    }
    valUnwrapper.reset();
    const currVal_8:any = import5.interpolate(1,'',valUnwrapper.unwrap(import5.castByValue(this._pipe_number_0_0,(<_View_ProductSliderComponent0>this.parent.parent)._pipe_number_0.transform)(this.context.$implicit.discountPercentage,'2.0-2')),'%');
    if ((valUnwrapper.hasWrappedValue || import5.checkBinding(throwOnChange,this._expr_8,currVal_8))) {
      this.renderer.setText(this._text_22,currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_3_3.ngOnDestroy();
  }
  private _handle_click_3_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.feedClick(this.context.$implicit,(this.context.index + 1))) !== false);
    const pd_1:any = ((<any>this._RouterLinkWithHref_3_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_ProductSliderComponent3(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ProductSliderComponent3(viewUtils,parentInjector,declarationEl);
}