/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './browser.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import7 from 'angular2-universal/browser/universal-module';
import * as import8 from '@angular/forms/src/directives';
import * as import9 from '@angular/forms/src/form_providers';
import * as import10 from '@angular/router/src/router_module';
import * as import11 from '@angularclass/idle-preload/dist/index';
import * as import12 from './+app/shared/shared.module';
import * as import13 from './+app/+home/home-routing.module';
import * as import14 from './+app/+swiper/swiper.module';
import * as import15 from './+app/shared/widgets/widgets.module';
import * as import16 from './+app/+home/home.module';
import * as import17 from './+app/+product/product.routing';
import * as import18 from './+app/+product/product.module';
import * as import19 from './+app/+listing/list-routing.module';
import * as import20 from './+app/+listing/listing.module';
import * as import21 from './+app/statics/statics-routing.module';
import * as import22 from './+app/statics/statics.module';
import * as import23 from './+app/app-routing.module';
import * as import24 from './+app/app.module';
import * as import25 from './+app/shared/cache.service';
import * as import26 from '@angular/common/src/localization';
import * as import27 from '@angular/core/src/application_init';
import * as import28 from '@angular/core/src/testability/testability';
import * as import29 from '@angular/core/src/application_ref';
import * as import30 from '@angular/core/src/linker/compiler';
import * as import31 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import32 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import33 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import34 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import35 from '@angular/core/src/linker/view_utils';
import * as import36 from '@angular/platform-browser/src/browser/title';
import * as import37 from '@angular/http/src/backends/browser_xhr';
import * as import38 from '@angular/http/src/base_response_options';
import * as import39 from '@angular/http/src/backends/xhr_backend';
import * as import40 from '@angular/http/src/base_request_options';
import * as import41 from '@angular/http/src/backends/browser_jsonp';
import * as import42 from '@angular/http/src/backends/jsonp_backend';
import * as import43 from '@angular/router/src/url_tree';
import * as import44 from '@angular/router/src/router_outlet_map';
import * as import45 from '@angular/common/src/location/location';
import * as import46 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import47 from '@angular/router/src/router_preloader';
import * as import48 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import49 from '@angular/forms/src/form_builder';
import * as import50 from './+app/shared/services/http-client.service';
import * as import51 from './+app/+product/product.service';
import * as import52 from './+app/+product/product-detail-resolve.service';
import * as import53 from './+app/+listing/listing.service';
import * as import54 from './+app/+listing/listing-resolve.service';
import * as import55 from './+app/+listing/filter-resolve.service';
import * as import56 from './+app/shared/services/router-header-binding.service';
import * as import57 from './+app/shared/services/data-holding.service';
import * as import58 from './+app/shared/api.service';
import * as import59 from './+app/shared/model/model.service';
import * as import60 from './angular2-meta';
import * as import61 from '@angular/core/src/di/injector';
import * as import62 from './+app/+home/home.component.ngfactory';
import * as import63 from './+app/shared/widgets/mega-menu/mega-menu.component.ngfactory';
import * as import64 from './+app/shared/widgets/mega-menu/mega-menu-link.component.ngfactory';
import * as import65 from './+app/shared/widgets/announcement-widget/announcement-widget.component.ngfactory';
import * as import66 from './+app/shared/widgets/category-widget/category-widget.component.ngfactory';
import * as import67 from './+app/shared/widgets/extra-menu/extra-menu.component.ngfactory';
import * as import68 from './+app/shared/widgets/hero-banner/hero-banner.component.ngfactory';
import * as import69 from './+app/shared/widgets/portfolio-widget/portfolio-widget.component.ngfactory';
import * as import70 from './+app/shared/widgets/storyline-widget/storyline-widget.component.ngfactory';
import * as import71 from './+app/shared/widgets/product-slider/product-slider.component.ngfactory';
import * as import72 from './+app/shared/widgets/testimonials-widget/testimonials-widget.component.ngfactory';
import * as import73 from './+app/shared/widgets/pagination/pagination.component.ngfactory';
import * as import74 from './+app/shared/widgets/product-card/product-card.component.ngfactory';
import * as import75 from './+app/+product/product.component.ngfactory';
import * as import76 from './+app/+listing/listing.component.ngfactory';
import * as import77 from './+app/statics/about-us/about-us.component.ngfactory';
import * as import78 from './+app/statics/faqs/faqs.component.ngfactory';
import * as import79 from './+app/statics/order-tracking/order-tracking.component.ngfactory';
import * as import80 from './+app/statics/in-media/in-media.component.ngfactory';
import * as import81 from './+app/statics/contact-us/contactus.component.ngfactory';
import * as import82 from './+app/+not_found/not-found.component.ngfactory';
import * as import83 from './+app/app.component.ngfactory';
import * as import84 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import85 from '@angular/platform-browser/src/dom/events/key_events';
import * as import86 from '@angular/core/src/zone/ng_zone';
import * as import87 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import88 from '@angular/common/src/location/platform_location';
import * as import89 from '@angular/common/src/location/location_strategy';
import * as import90 from './+app/+home/home.component';
import * as import91 from './+app/+product/product.component';
import * as import92 from './+app/+listing/listing.component';
import * as import93 from './+app/statics/about-us/about-us.component';
import * as import94 from './+app/statics/faqs/faqs.component';
import * as import95 from './+app/statics/order-tracking/order-tracking.component';
import * as import96 from './+app/statics/in-media/in-media.component';
import * as import97 from './+app/statics/contact-us/contactus.component';
import * as import98 from './+app/+not_found/not-found.component';
import * as import99 from 'angular2-universal/browser/env';
import * as import100 from '@angular/router/src/router';
import * as import101 from '@angular/core/src/console';
import * as import102 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import103 from '@angular/core/src/i18n/tokens';
import * as import104 from '@angular/core/src/error_handler';
import * as import105 from '@angular/core/src/application_tokens';
import * as import106 from '@angular/platform-browser/src/dom/animation_driver';
import * as import107 from '@angular/core/src/render/api';
import * as import108 from '@angular/core/src/security';
import * as import109 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import110 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import111 from '@angular/http/src/interfaces';
import * as import112 from '@angular/http/src/http';
import * as import113 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import114 from '@angular/router/src/router_config_loader';
import * as import115 from '@angular/router/src/router_state';
class MainModuleInjector extends import0.NgModuleInjector<import1.MainModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _HttpModule_3:import5.HttpModule;
  _JsonpModule_4:import5.JsonpModule;
  _DOCUMENT_5:any;
  _DomSharedStylesHost_6:import6.DomSharedStylesHost;
  _SharedStylesHost_7:any;
  _UniversalModule_8:import7.UniversalModule;
  _InternalFormsSharedModule_9:import8.InternalFormsSharedModule;
  _FormsModule_10:import9.FormsModule;
  _ROUTER_FORROOT_GUARD_11:any;
  _RouterModule_12:import10.RouterModule;
  _IdlePreloadModule_13:import11.IdlePreloadModule;
  _ReactiveFormsModule_14:import9.ReactiveFormsModule;
  _SharedModule_15:import12.SharedModule;
  _HomeRoutingModule_16:import13.HomeRoutingModule;
  _SwiperModule_17:import14.SwiperModule;
  _WidgetModule_18:import15.WidgetModule;
  _HomeModule_19:import16.HomeModule;
  _ProductRoutingModule_20:import17.ProductRoutingModule;
  _ProductModule_21:import18.ProductModule;
  _ListRoutingModule_22:import19.ListRoutingModule;
  _ListingModule_23:import20.ListingModule;
  _StaticsRoutingModule_24:import21.StaticsRoutingModule;
  _StaticsModule_25:import22.StaticsModule;
  _AppRoutingModule_26:import23.AppRoutingModule;
  _AppModule_27:import24.AppModule;
  _LRU_28:any;
  _CacheService_29:import25.CacheService;
  _MainModule_30:import1.MainModule;
  __LOCALE_ID_31:any;
  __NgLocalization_32:import26.NgLocaleLocalization;
  _ErrorHandler_33:any;
  _ApplicationInitStatus_34:import27.ApplicationInitStatus;
  _Testability_35:import28.Testability;
  _ApplicationRef__36:import29.ApplicationRef_;
  __ApplicationRef_37:any;
  __Compiler_38:import30.Compiler;
  __APP_ID_39:any;
  __HAMMER_GESTURE_CONFIG_40:import31.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_41:any[];
  __EventManager_42:import32.EventManager;
  __AnimationDriver_43:any;
  __DomRootRenderer_44:import33.DomRootRenderer_;
  __RootRenderer_45:any;
  __DomSanitizer_46:import34.DomSanitizerImpl;
  __Sanitizer_47:any;
  __ViewUtils_48:import35.ViewUtils;
  __IterableDiffers_49:any;
  __KeyValueDiffers_50:any;
  __Title_51:import36.Title;
  __BrowserXhr_52:import37.BrowserXhr;
  __ResponseOptions_53:import38.BaseResponseOptions;
  __XSRFStrategy_54:any;
  __XHRBackend_55:import39.XHRBackend;
  __RequestOptions_56:import40.BaseRequestOptions;
  __Http_57:any;
  __BrowserJsonp_58:import41.BrowserJsonp;
  __JSONPBackend_59:import42.JSONPBackend_;
  __Jsonp_60:any;
  __UNIVERSAL_CACHE_61:any;
  __AUTO_PREBOOT_62:any;
  __UrlSerializer_63:import43.DefaultUrlSerializer;
  __RouterOutletMap_64:import44.RouterOutletMap;
  __ROUTER_CONFIGURATION_65:any;
  __LocationStrategy_66:any;
  __Location_67:import45.Location;
  __NgModuleFactoryLoader_68:import46.SystemJsNgModuleLoader;
  __ROUTES_69:any[];
  __Router_70:any;
  __REQUEST_IDLE_CALLBACK_71:any;
  __IdlePreload_72:import11.IdlePreload;
  __PreloadingStrategy_73:any;
  _RouterPreloader_74:import47.RouterPreloader;
  __APP_BOOTSTRAP_LISTENER_75:any[];
  __RadioControlRegistry_76:import48.RadioControlRegistry;
  __FormBuilder_77:import49.FormBuilder;
  __HttpClientService_78:import50.HttpClientService;
  __ProductService_79:import51.ProductService;
  __ProductDetailResolve_80:import52.ProductDetailResolve;
  __ListingService_81:import53.ListingService;
  __ListingResolveService_82:import54.ListingResolveService;
  __FilterResolveService_83:import55.FilterResolveService;
  __RouterHeaderBindingService_84:import56.RouterHeaderBindingService;
  __DataHoldingService_85:import57.DataHoldingService;
  __ActivatedRoute_86:any;
  __NoPreloading_87:import47.NoPreloading;
  __PreloadAllModules_88:import47.PreloadAllModules;
  __ApiService_89:import58.ApiService;
  __ModelService_90:import59.ModelService;
  __isBrowser_91:any;
  __isNode_92:any;
  __req_93:any;
  __res_94:any;
  __Meta_95:import60.Meta;
  constructor(parent:import61.Injector) {
    super(parent,[
      import62.HomeComponentNgFactory,
      import63.MegaMenuComponentNgFactory,
      import64.MegaMenuLinkComponentNgFactory,
      import65.AnnouncementWidgetComponentNgFactory,
      import66.CategoryWidgetComponentNgFactory,
      import67.ExtraMenuComponentNgFactory,
      import68.HeroBannerComponentNgFactory,
      import69.PortfolioWidgetComponentNgFactory,
      import70.StorylineWidgetComponentNgFactory,
      import71.ProductSliderComponentNgFactory,
      import72.TestimonialsWidgetComponentNgFactory,
      import73.PaginationComponentNgFactory,
      import74.ProductCardComponentNgFactory,
      import75.ProductComponentNgFactory,
      import75.ProductComponentNgFactory,
      import76.ListingComponentNgFactory,
      import76.ListingComponentNgFactory,
      import76.ListingComponentNgFactory,
      import77.AboutUsComponentNgFactory,
      import78.FaqsComponentNgFactory,
      import79.OrderTrackingComponentNgFactory,
      import80.InMediaComponentNgFactory,
      import81.ContactUsComponentNgFactory,
      import82.NotFoundComponentNgFactory,
      import83.AppComponentNgFactory
    ]
    ,[import83.AppComponentNgFactory]);
  }
  get _LOCALE_ID_31():any {
    if ((this.__LOCALE_ID_31 == (null as any))) { (this.__LOCALE_ID_31 = 'en-US'); }
    return this.__LOCALE_ID_31;
  }
  get _NgLocalization_32():import26.NgLocaleLocalization {
    if ((this.__NgLocalization_32 == (null as any))) { (this.__NgLocalization_32 = new import26.NgLocaleLocalization(this._LOCALE_ID_31)); }
    return this.__NgLocalization_32;
  }
  get _ApplicationRef_37():any {
    if ((this.__ApplicationRef_37 == (null as any))) { (this.__ApplicationRef_37 = this._ApplicationRef__36); }
    return this.__ApplicationRef_37;
  }
  get _Compiler_38():import30.Compiler {
    if ((this.__Compiler_38 == (null as any))) { (this.__Compiler_38 = new import30.Compiler()); }
    return this.__Compiler_38;
  }
  get _APP_ID_39():any {
    if ((this.__APP_ID_39 == (null as any))) { (this.__APP_ID_39 = import7.appIdFactory()); }
    return this.__APP_ID_39;
  }
  get _HAMMER_GESTURE_CONFIG_40():import31.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_40 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_40 = new import31.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_40;
  }
  get _EVENT_MANAGER_PLUGINS_41():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_41 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_41 = [
      new import84.DomEventsPlugin(),
      new import85.KeyEventsPlugin(),
      new import31.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_40)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_41;
  }
  get _EventManager_42():import32.EventManager {
    if ((this.__EventManager_42 == (null as any))) { (this.__EventManager_42 = new import32.EventManager(this._EVENT_MANAGER_PLUGINS_41,this.parent.get(import86.NgZone))); }
    return this.__EventManager_42;
  }
  get _AnimationDriver_43():any {
    if ((this.__AnimationDriver_43 == (null as any))) { (this.__AnimationDriver_43 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_43;
  }
  get _DomRootRenderer_44():import33.DomRootRenderer_ {
    if ((this.__DomRootRenderer_44 == (null as any))) { (this.__DomRootRenderer_44 = new import33.DomRootRenderer_(this._DOCUMENT_5,this._EventManager_42,this._DomSharedStylesHost_6,this._AnimationDriver_43)); }
    return this.__DomRootRenderer_44;
  }
  get _RootRenderer_45():any {
    if ((this.__RootRenderer_45 == (null as any))) { (this.__RootRenderer_45 = import87._createConditionalRootRenderer(this._DomRootRenderer_44,this.parent.get(import87.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_45;
  }
  get _DomSanitizer_46():import34.DomSanitizerImpl {
    if ((this.__DomSanitizer_46 == (null as any))) { (this.__DomSanitizer_46 = new import34.DomSanitizerImpl()); }
    return this.__DomSanitizer_46;
  }
  get _Sanitizer_47():any {
    if ((this.__Sanitizer_47 == (null as any))) { (this.__Sanitizer_47 = this._DomSanitizer_46); }
    return this.__Sanitizer_47;
  }
  get _ViewUtils_48():import35.ViewUtils {
    if ((this.__ViewUtils_48 == (null as any))) { (this.__ViewUtils_48 = new import35.ViewUtils(this._RootRenderer_45,this._APP_ID_39,this._Sanitizer_47)); }
    return this.__ViewUtils_48;
  }
  get _IterableDiffers_49():any {
    if ((this.__IterableDiffers_49 == (null as any))) { (this.__IterableDiffers_49 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_49;
  }
  get _KeyValueDiffers_50():any {
    if ((this.__KeyValueDiffers_50 == (null as any))) { (this.__KeyValueDiffers_50 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_50;
  }
  get _Title_51():import36.Title {
    if ((this.__Title_51 == (null as any))) { (this.__Title_51 = new import36.Title()); }
    return this.__Title_51;
  }
  get _BrowserXhr_52():import37.BrowserXhr {
    if ((this.__BrowserXhr_52 == (null as any))) { (this.__BrowserXhr_52 = new import37.BrowserXhr()); }
    return this.__BrowserXhr_52;
  }
  get _ResponseOptions_53():import38.BaseResponseOptions {
    if ((this.__ResponseOptions_53 == (null as any))) { (this.__ResponseOptions_53 = new import38.BaseResponseOptions()); }
    return this.__ResponseOptions_53;
  }
  get _XSRFStrategy_54():any {
    if ((this.__XSRFStrategy_54 == (null as any))) { (this.__XSRFStrategy_54 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_54;
  }
  get _XHRBackend_55():import39.XHRBackend {
    if ((this.__XHRBackend_55 == (null as any))) { (this.__XHRBackend_55 = new import39.XHRBackend(this._BrowserXhr_52,this._ResponseOptions_53,this._XSRFStrategy_54)); }
    return this.__XHRBackend_55;
  }
  get _RequestOptions_56():import40.BaseRequestOptions {
    if ((this.__RequestOptions_56 == (null as any))) { (this.__RequestOptions_56 = new import40.BaseRequestOptions()); }
    return this.__RequestOptions_56;
  }
  get _Http_57():any {
    if ((this.__Http_57 == (null as any))) { (this.__Http_57 = import5.httpFactory(this._XHRBackend_55,this._RequestOptions_56)); }
    return this.__Http_57;
  }
  get _BrowserJsonp_58():import41.BrowserJsonp {
    if ((this.__BrowserJsonp_58 == (null as any))) { (this.__BrowserJsonp_58 = new import41.BrowserJsonp()); }
    return this.__BrowserJsonp_58;
  }
  get _JSONPBackend_59():import42.JSONPBackend_ {
    if ((this.__JSONPBackend_59 == (null as any))) { (this.__JSONPBackend_59 = new import42.JSONPBackend_(this._BrowserJsonp_58,this._ResponseOptions_53)); }
    return this.__JSONPBackend_59;
  }
  get _Jsonp_60():any {
    if ((this.__Jsonp_60 == (null as any))) { (this.__Jsonp_60 = import5.jsonpFactory(this._JSONPBackend_59,this._RequestOptions_56)); }
    return this.__Jsonp_60;
  }
  get _UNIVERSAL_CACHE_61():any {
    if ((this.__UNIVERSAL_CACHE_61 == (null as any))) { (this.__UNIVERSAL_CACHE_61 = import7.universalCacheFactory()); }
    return this.__UNIVERSAL_CACHE_61;
  }
  get _AUTO_PREBOOT_62():any {
    if ((this.__AUTO_PREBOOT_62 == (null as any))) { (this.__AUTO_PREBOOT_62 = true); }
    return this.__AUTO_PREBOOT_62;
  }
  get _UrlSerializer_63():import43.DefaultUrlSerializer {
    if ((this.__UrlSerializer_63 == (null as any))) { (this.__UrlSerializer_63 = new import43.DefaultUrlSerializer()); }
    return this.__UrlSerializer_63;
  }
  get _RouterOutletMap_64():import44.RouterOutletMap {
    if ((this.__RouterOutletMap_64 == (null as any))) { (this.__RouterOutletMap_64 = new import44.RouterOutletMap()); }
    return this.__RouterOutletMap_64;
  }
  get _ROUTER_CONFIGURATION_65():any {
    if ((this.__ROUTER_CONFIGURATION_65 == (null as any))) { (this.__ROUTER_CONFIGURATION_65 = {
      useHash: false,
      preloadingStrategy: import11.IdlePreload
    }
    ); }
    return this.__ROUTER_CONFIGURATION_65;
  }
  get _LocationStrategy_66():any {
    if ((this.__LocationStrategy_66 == (null as any))) { (this.__LocationStrategy_66 = import10.provideLocationStrategy(this.parent.get(import88.PlatformLocation),this.parent.get(import89.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_65)); }
    return this.__LocationStrategy_66;
  }
  get _Location_67():import45.Location {
    if ((this.__Location_67 == (null as any))) { (this.__Location_67 = new import45.Location(this._LocationStrategy_66)); }
    return this.__Location_67;
  }
  get _NgModuleFactoryLoader_68():import46.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_68 == (null as any))) { (this.__NgModuleFactoryLoader_68 = new import46.SystemJsNgModuleLoader(this._Compiler_38,this.parent.get(import46.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_68;
  }
  get _ROUTES_69():any[] {
    if ((this.__ROUTES_69 == (null as any))) { (this.__ROUTES_69 = [
        [{
          path: '',
          component: import90.HomeComponent
        }
      ],
      [
        {
          path: 'product/:id',
          component: import91.ProductComponent,
          pathMatch: 'full',
          resolve: {product: import52.ProductDetailResolve}
        }
        ,
        {
          path: 'shop/:slug/:id',
          component: import91.ProductComponent,
          pathMatch: 'full',
          resolve: {product: import52.ProductDetailResolve}
        }

      ]
      ,
      [
        {
          path: 'category',
          component: import92.ListingComponent,
          resolve: {filters: import55.FilterResolveService}
        }
        ,
        {
          path: 'premium',
          component: import92.ListingComponent,
          resolve: {filters: import55.FilterResolveService}
        }
        ,
        {
          path: 'category/:id',
          component: import92.ListingComponent,
          resolve: {filters: import55.FilterResolveService}
        }

      ]
      ,
      [
        {
          path: 'about_us',
          component: import93.AboutUsComponent
        }
        ,
        {
          path: 'faqs',
          component: import94.FaqsComponent
        }
        ,
        {
          path: 'order_tracking',
          component: import95.OrderTrackingComponent
        }
        ,
        {
          path: 'craftsvilla_in_media',
          component: import96.InMediaComponent
        }
        ,
        {
          path: 'contactus',
          component: import97.ContactUsComponent
        }

      ]
      ,
      [
        {
          path: '404',
          component: import98.NotFoundComponent
        }
        ,
        {
          path: '**',
          redirectTo: '404'
        }

      ]
      ,
      ([] as any[])
    ]
    ); }
    return this.__ROUTES_69;
  }
  get _Router_70():any {
    if ((this.__Router_70 == (null as any))) { (this.__Router_70 = import10.setupRouter(this._ApplicationRef_37,this._UrlSerializer_63,this._RouterOutletMap_64,this._Location_67,this,this._NgModuleFactoryLoader_68,this._Compiler_38,this._ROUTES_69,this._ROUTER_CONFIGURATION_65)); }
    return this.__Router_70;
  }
  get _REQUEST_IDLE_CALLBACK_71():any {
    if ((this.__REQUEST_IDLE_CALLBACK_71 == (null as any))) { (this.__REQUEST_IDLE_CALLBACK_71 = import11._requestIdle(this.parent.get(import86.NgZone))); }
    return this.__REQUEST_IDLE_CALLBACK_71;
  }
  get _IdlePreload_72():import11.IdlePreload {
    if ((this.__IdlePreload_72 == (null as any))) { (this.__IdlePreload_72 = new import11.IdlePreload(this.parent.get(import86.NgZone),this._REQUEST_IDLE_CALLBACK_71)); }
    return this.__IdlePreload_72;
  }
  get _PreloadingStrategy_73():any {
    if ((this.__PreloadingStrategy_73 == (null as any))) { (this.__PreloadingStrategy_73 = this._IdlePreload_72); }
    return this.__PreloadingStrategy_73;
  }
  get _APP_BOOTSTRAP_LISTENER_75():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_75 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_75 = [
      import7.appBootstrapListenerFactory(this._AUTO_PREBOOT_62),
      import10.initialRouterNavigation(this._Router_70,this._ApplicationRef_37,this._RouterPreloader_74,this._ROUTER_CONFIGURATION_65)
    ]
    ); }
    return this.__APP_BOOTSTRAP_LISTENER_75;
  }
  get _RadioControlRegistry_76():import48.RadioControlRegistry {
    if ((this.__RadioControlRegistry_76 == (null as any))) { (this.__RadioControlRegistry_76 = new import48.RadioControlRegistry()); }
    return this.__RadioControlRegistry_76;
  }
  get _FormBuilder_77():import49.FormBuilder {
    if ((this.__FormBuilder_77 == (null as any))) { (this.__FormBuilder_77 = new import49.FormBuilder()); }
    return this.__FormBuilder_77;
  }
  get _HttpClientService_78():import50.HttpClientService {
    if ((this.__HttpClientService_78 == (null as any))) { (this.__HttpClientService_78 = new import50.HttpClientService(this._Http_57)); }
    return this.__HttpClientService_78;
  }
  get _ProductService_79():import51.ProductService {
    if ((this.__ProductService_79 == (null as any))) { (this.__ProductService_79 = new import51.ProductService(this._HttpClientService_78)); }
    return this.__ProductService_79;
  }
  get _ProductDetailResolve_80():import52.ProductDetailResolve {
    if ((this.__ProductDetailResolve_80 == (null as any))) { (this.__ProductDetailResolve_80 = new import52.ProductDetailResolve(this._ProductService_79,this._Router_70)); }
    return this.__ProductDetailResolve_80;
  }
  get _ListingService_81():import53.ListingService {
    if ((this.__ListingService_81 == (null as any))) { (this.__ListingService_81 = new import53.ListingService(this._HttpClientService_78)); }
    return this.__ListingService_81;
  }
  get _ListingResolveService_82():import54.ListingResolveService {
    if ((this.__ListingResolveService_82 == (null as any))) { (this.__ListingResolveService_82 = new import54.ListingResolveService(this._ListingService_81,this._Router_70)); }
    return this.__ListingResolveService_82;
  }
  get _FilterResolveService_83():import55.FilterResolveService {
    if ((this.__FilterResolveService_83 == (null as any))) { (this.__FilterResolveService_83 = new import55.FilterResolveService(this._ListingService_81,this._Router_70)); }
    return this.__FilterResolveService_83;
  }
  get _RouterHeaderBindingService_84():import56.RouterHeaderBindingService {
    if ((this.__RouterHeaderBindingService_84 == (null as any))) { (this.__RouterHeaderBindingService_84 = new import56.RouterHeaderBindingService()); }
    return this.__RouterHeaderBindingService_84;
  }
  get _DataHoldingService_85():import57.DataHoldingService {
    if ((this.__DataHoldingService_85 == (null as any))) { (this.__DataHoldingService_85 = new import57.DataHoldingService()); }
    return this.__DataHoldingService_85;
  }
  get _ActivatedRoute_86():any {
    if ((this.__ActivatedRoute_86 == (null as any))) { (this.__ActivatedRoute_86 = import10.rootRoute(this._Router_70)); }
    return this.__ActivatedRoute_86;
  }
  get _NoPreloading_87():import47.NoPreloading {
    if ((this.__NoPreloading_87 == (null as any))) { (this.__NoPreloading_87 = new import47.NoPreloading()); }
    return this.__NoPreloading_87;
  }
  get _PreloadAllModules_88():import47.PreloadAllModules {
    if ((this.__PreloadAllModules_88 == (null as any))) { (this.__PreloadAllModules_88 = new import47.PreloadAllModules()); }
    return this.__PreloadAllModules_88;
  }
  get _ApiService_89():import58.ApiService {
    if ((this.__ApiService_89 == (null as any))) { (this.__ApiService_89 = new import58.ApiService(this._Http_57)); }
    return this.__ApiService_89;
  }
  get _ModelService_90():import59.ModelService {
    if ((this.__ModelService_90 == (null as any))) { (this.__ModelService_90 = new import59.ModelService(this._ApiService_89,this._CacheService_29)); }
    return this.__ModelService_90;
  }
  get _isBrowser_91():any {
    if ((this.__isBrowser_91 == (null as any))) { (this.__isBrowser_91 = true); }
    return this.__isBrowser_91;
  }
  get _isNode_92():any {
    if ((this.__isNode_92 == (null as any))) { (this.__isNode_92 = import99.isNode); }
    return this.__isNode_92;
  }
  get _req_93():any {
    if ((this.__req_93 == (null as any))) { (this.__req_93 = import1.getRequest()); }
    return this.__req_93;
  }
  get _res_94():any {
    if ((this.__res_94 == (null as any))) { (this.__res_94 = import1.getResponse()); }
    return this.__res_94;
  }
  get _Meta_95():import60.Meta {
    if ((this.__Meta_95 == (null as any))) { (this.__Meta_95 = new import60.Meta()); }
    return this.__Meta_95;
  }
  createInternal():import1.MainModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_3 = new import5.HttpModule();
    this._JsonpModule_4 = new import5.JsonpModule();
    this._DOCUMENT_5 = import4._document();
    this._DomSharedStylesHost_6 = new import6.DomSharedStylesHost(this._DOCUMENT_5);
    this._SharedStylesHost_7 = this._DomSharedStylesHost_6;
    this._UniversalModule_8 = new import7.UniversalModule(this._SharedStylesHost_7);
    this._InternalFormsSharedModule_9 = new import8.InternalFormsSharedModule();
    this._FormsModule_10 = new import9.FormsModule();
    this._ROUTER_FORROOT_GUARD_11 = import10.provideForRootGuard(this.parent.get(import100.Router,(null as any)));
    this._RouterModule_12 = new import10.RouterModule(this._ROUTER_FORROOT_GUARD_11);
    this._IdlePreloadModule_13 = new import11.IdlePreloadModule();
    this._ReactiveFormsModule_14 = new import9.ReactiveFormsModule();
    this._SharedModule_15 = new import12.SharedModule();
    this._HomeRoutingModule_16 = new import13.HomeRoutingModule();
    this._SwiperModule_17 = new import14.SwiperModule();
    this._WidgetModule_18 = new import15.WidgetModule();
    this._HomeModule_19 = new import16.HomeModule();
    this._ProductRoutingModule_20 = new import17.ProductRoutingModule();
    this._ProductModule_21 = new import18.ProductModule();
    this._ListRoutingModule_22 = new import19.ListRoutingModule();
    this._ListingModule_23 = new import20.ListingModule();
    this._StaticsRoutingModule_24 = new import21.StaticsRoutingModule();
    this._StaticsModule_25 = new import22.StaticsModule();
    this._AppRoutingModule_26 = new import23.AppRoutingModule();
    this._AppModule_27 = new import24.AppModule();
    this._LRU_28 = import1.getLRU();
    this._CacheService_29 = new import25.CacheService(this._LRU_28);
    this._MainModule_30 = new import1.MainModule(this._CacheService_29);
    this._ErrorHandler_33 = import4.errorHandler();
    this._ApplicationInitStatus_34 = new import27.ApplicationInitStatus(this.parent.get(import27.APP_INITIALIZER,(null as any)));
    this._Testability_35 = new import28.Testability(this.parent.get(import86.NgZone));
    this._ApplicationRef__36 = new import29.ApplicationRef_(this.parent.get(import86.NgZone),this.parent.get(import101.Console),this,this._ErrorHandler_33,this,this._ApplicationInitStatus_34,this.parent.get(import28.TestabilityRegistry,(null as any)),this._Testability_35);
    this._RouterPreloader_74 = new import47.RouterPreloader(this._Router_70,this._NgModuleFactoryLoader_68,this._Compiler_38,this,this._PreloadingStrategy_73);
    return this._MainModule_30;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import5.JsonpModule)) { return this._JsonpModule_4; }
    if ((token === import102.DOCUMENT)) { return this._DOCUMENT_5; }
    if ((token === import6.DomSharedStylesHost)) { return this._DomSharedStylesHost_6; }
    if ((token === import6.SharedStylesHost)) { return this._SharedStylesHost_7; }
    if ((token === import7.UniversalModule)) { return this._UniversalModule_8; }
    if ((token === import8.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_9; }
    if ((token === import9.FormsModule)) { return this._FormsModule_10; }
    if ((token === import10.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_11; }
    if ((token === import10.RouterModule)) { return this._RouterModule_12; }
    if ((token === import11.IdlePreloadModule)) { return this._IdlePreloadModule_13; }
    if ((token === import9.ReactiveFormsModule)) { return this._ReactiveFormsModule_14; }
    if ((token === import12.SharedModule)) { return this._SharedModule_15; }
    if ((token === import13.HomeRoutingModule)) { return this._HomeRoutingModule_16; }
    if ((token === import14.SwiperModule)) { return this._SwiperModule_17; }
    if ((token === import15.WidgetModule)) { return this._WidgetModule_18; }
    if ((token === import16.HomeModule)) { return this._HomeModule_19; }
    if ((token === import17.ProductRoutingModule)) { return this._ProductRoutingModule_20; }
    if ((token === import18.ProductModule)) { return this._ProductModule_21; }
    if ((token === import19.ListRoutingModule)) { return this._ListRoutingModule_22; }
    if ((token === import20.ListingModule)) { return this._ListingModule_23; }
    if ((token === import21.StaticsRoutingModule)) { return this._StaticsRoutingModule_24; }
    if ((token === import22.StaticsModule)) { return this._StaticsModule_25; }
    if ((token === import23.AppRoutingModule)) { return this._AppRoutingModule_26; }
    if ((token === import24.AppModule)) { return this._AppModule_27; }
    if ((token === 'LRU')) { return this._LRU_28; }
    if ((token === import25.CacheService)) { return this._CacheService_29; }
    if ((token === import1.MainModule)) { return this._MainModule_30; }
    if ((token === import103.LOCALE_ID)) { return this._LOCALE_ID_31; }
    if ((token === import26.NgLocalization)) { return this._NgLocalization_32; }
    if ((token === import104.ErrorHandler)) { return this._ErrorHandler_33; }
    if ((token === import27.ApplicationInitStatus)) { return this._ApplicationInitStatus_34; }
    if ((token === import28.Testability)) { return this._Testability_35; }
    if ((token === import29.ApplicationRef_)) { return this._ApplicationRef__36; }
    if ((token === import29.ApplicationRef)) { return this._ApplicationRef_37; }
    if ((token === import30.Compiler)) { return this._Compiler_38; }
    if ((token === import105.APP_ID)) { return this._APP_ID_39; }
    if ((token === import31.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_40; }
    if ((token === import32.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_41; }
    if ((token === import32.EventManager)) { return this._EventManager_42; }
    if ((token === import106.AnimationDriver)) { return this._AnimationDriver_43; }
    if ((token === import33.DomRootRenderer)) { return this._DomRootRenderer_44; }
    if ((token === import107.RootRenderer)) { return this._RootRenderer_45; }
    if ((token === import34.DomSanitizer)) { return this._DomSanitizer_46; }
    if ((token === import108.Sanitizer)) { return this._Sanitizer_47; }
    if ((token === import35.ViewUtils)) { return this._ViewUtils_48; }
    if ((token === import109.IterableDiffers)) { return this._IterableDiffers_49; }
    if ((token === import110.KeyValueDiffers)) { return this._KeyValueDiffers_50; }
    if ((token === import36.Title)) { return this._Title_51; }
    if ((token === import37.BrowserXhr)) { return this._BrowserXhr_52; }
    if ((token === import38.ResponseOptions)) { return this._ResponseOptions_53; }
    if ((token === import111.XSRFStrategy)) { return this._XSRFStrategy_54; }
    if ((token === import39.XHRBackend)) { return this._XHRBackend_55; }
    if ((token === import40.RequestOptions)) { return this._RequestOptions_56; }
    if ((token === import112.Http)) { return this._Http_57; }
    if ((token === import41.BrowserJsonp)) { return this._BrowserJsonp_58; }
    if ((token === import42.JSONPBackend)) { return this._JSONPBackend_59; }
    if ((token === import112.Jsonp)) { return this._Jsonp_60; }
    if ((token === import7.UNIVERSAL_CACHE)) { return this._UNIVERSAL_CACHE_61; }
    if ((token === import7.AUTO_PREBOOT)) { return this._AUTO_PREBOOT_62; }
    if ((token === import43.UrlSerializer)) { return this._UrlSerializer_63; }
    if ((token === import44.RouterOutletMap)) { return this._RouterOutletMap_64; }
    if ((token === import10.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_65; }
    if ((token === import89.LocationStrategy)) { return this._LocationStrategy_66; }
    if ((token === import45.Location)) { return this._Location_67; }
    if ((token === import113.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_68; }
    if ((token === import114.ROUTES)) { return this._ROUTES_69; }
    if ((token === import100.Router)) { return this._Router_70; }
    if ((token === import11.REQUEST_IDLE_CALLBACK)) { return this._REQUEST_IDLE_CALLBACK_71; }
    if ((token === import11.IdlePreload)) { return this._IdlePreload_72; }
    if ((token === import47.PreloadingStrategy)) { return this._PreloadingStrategy_73; }
    if ((token === import47.RouterPreloader)) { return this._RouterPreloader_74; }
    if ((token === import105.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_75; }
    if ((token === import48.RadioControlRegistry)) { return this._RadioControlRegistry_76; }
    if ((token === import49.FormBuilder)) { return this._FormBuilder_77; }
    if ((token === import50.HttpClientService)) { return this._HttpClientService_78; }
    if ((token === import51.ProductService)) { return this._ProductService_79; }
    if ((token === import52.ProductDetailResolve)) { return this._ProductDetailResolve_80; }
    if ((token === import53.ListingService)) { return this._ListingService_81; }
    if ((token === import54.ListingResolveService)) { return this._ListingResolveService_82; }
    if ((token === import55.FilterResolveService)) { return this._FilterResolveService_83; }
    if ((token === import56.RouterHeaderBindingService)) { return this._RouterHeaderBindingService_84; }
    if ((token === import57.DataHoldingService)) { return this._DataHoldingService_85; }
    if ((token === import115.ActivatedRoute)) { return this._ActivatedRoute_86; }
    if ((token === import47.NoPreloading)) { return this._NoPreloading_87; }
    if ((token === import47.PreloadAllModules)) { return this._PreloadAllModules_88; }
    if ((token === import58.ApiService)) { return this._ApiService_89; }
    if ((token === import59.ModelService)) { return this._ModelService_90; }
    if ((token === 'isBrowser')) { return this._isBrowser_91; }
    if ((token === 'isNode')) { return this._isNode_92; }
    if ((token === 'req')) { return this._req_93; }
    if ((token === 'res')) { return this._res_94; }
    if ((token === import60.Meta)) { return this._Meta_95; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__36.ngOnDestroy();
    this._RouterPreloader_74.ngOnDestroy();
  }
}
export const MainModuleNgFactory:import0.NgModuleFactory<import1.MainModule> = new import0.NgModuleFactory(MainModuleInjector,import1.MainModule);