/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.pagination-page[_ngcontent-%COMP%], .pagination-next[_ngcontent-%COMP%], .pagination-prev[_ngcontent-%COMP%] {\n    cursor: pointer;\n}'];