/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../../app/shared/services/cart-details.service';
import * as import4 from '../../../../../app/shared/widgets/header/header.component';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/linker/component_factory_resolver';
import * as import10 from '../mega-menu/mega-menu.component.ngfactory';
import * as import11 from '../../../../../app/shared/services/http-client.service';
import * as import12 from '@angular/router/src/router';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from './header.component.css.shim';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from '@angular/common/src/directives/ng_if';
import * as import18 from '@angular/common/src/directives/ng_class';
import * as import19 from '@angular/forms/src/directives/default_value_accessor';
import * as import20 from '@angular/forms/src/directives/ng_model';
import * as import21 from '@angular/forms/src/directives/ng_control_status';
import * as import22 from '@angular/common/src/directives/ng_style';
import * as import23 from '@angular/core/src/linker/template_ref';
import * as import24 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import25 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from '@angular/forms/src/directives/control_value_accessor';
import * as import28 from '@angular/forms/src/directives/ng_control';
import * as import29 from '@angular/common/src/directives/ng_for';
import * as import30 from '../../../../../app/shared/widgets/tabs-widget/tabs.component';
import * as import31 from '../../../../../app/shared/widgets/tabs-widget/tab.component';
import * as import32 from '../tabs-widget/tabs.component.ngfactory';
import * as import33 from '../tabs-widget/tab.component.ngfactory';
import * as import34 from '@angular/router/src/directives/router_link';
import * as import35 from '@angular/router/src/router_state';
import * as import36 from '@angular/common/src/location/location_strategy';
import * as import37 from '@angular/core/src/security';
var renderType_HeaderComponent_Host:import0.RenderComponentType = (null as any);
class _View_HeaderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ComponentFactoryResolver_0_4:any;
  _CartDetailsService_0_5:import3.CartDetailsService;
  _HeaderComponent_0_6:import4.HeaderComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent_Host0,renderType_HeaderComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('cvi-header',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ComponentFactoryResolver_0_4 = new import9.CodegenComponentFactoryResolver([import10.MegaMenuComponentNgFactory],this.parentInjector.get(import9.ComponentFactoryResolver));
    this._CartDetailsService_0_5 = new import3.CartDetailsService(this.parentInjector.get(import11.HttpClientService));
    this._HeaderComponent_0_6 = new import4.HeaderComponent(this.parentInjector.get(import12.Router),this._ComponentFactoryResolver_0_4,this._CartDetailsService_0_5);
    this._appEl_0.initComponent(this._HeaderComponent_0_6,[],compView_0);
    compView_0.create(this._HeaderComponent_0_6,this.projectableNodes,(null as any));
    var disposable_0:Function = this.renderer.listenGlobal('window','scroll',this.eventHandler(this._handle_scroll_0_0.bind(this)));
    this.init([].concat([this._el_0]),[this._el_0],[disposable_0],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.ComponentFactoryResolver) && (0 === requestNodeIndex))) { return this._ComponentFactoryResolver_0_4; }
    if (((token === import3.CartDetailsService) && (0 === requestNodeIndex))) { return this._CartDetailsService_0_5; }
    if (((token === import4.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeaderComponent_0_6.ngOnInit(); }
    if (!throwOnChange) { this._HeaderComponent_0_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_scroll_0_0($event:any):boolean {
    this._appEl_0.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._HeaderComponent_0_6.hideMegaMenuOnScroll($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeaderComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HeaderComponent_Host === (null as any))) { (renderType_HeaderComponent_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_HeaderComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HeaderComponentNgFactory:import14.ComponentFactory<import4.HeaderComponent> = new import14.ComponentFactory<import4.HeaderComponent>('cvi-header',viewFactory_HeaderComponent_Host0,import4.HeaderComponent);
const styles_HeaderComponent:any[] = [import15.styles];
var renderType_HeaderComponent:import0.RenderComponentType = (null as any);
class _View_HeaderComponent0 extends import1.AppView<import4.HeaderComponent> {
  _viewQuery_headerContent_0:import16.QueryList<any>;
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import17.NgIf;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import17.NgIf;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import17.NgIf;
  _text_16:any;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import17.NgIf;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _TemplateRef_22_5:any;
  _NgIf_22_6:import17.NgIf;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _NgClass_28_3:import18.NgClass;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _el_33:any;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _appEl_35:import2.AppElement;
  _TemplateRef_35_5:any;
  _NgIf_35_6:import17.NgIf;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _NgClass_38_3:import18.NgClass;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _DefaultValueAccessor_42_3:import19.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_42_4:any[];
  _NgModel_42_5:import20.NgModel;
  _NgControl_42_6:any;
  _NgControlStatus_42_7:import21.NgControlStatus;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _NgClass_79_3:import18.NgClass;
  _NgStyle_79_4:import22.NgStyle;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _el_83:any;
  /*private*/ _appEl_83:import2.AppElement;
  _text_84:any;
  _text_85:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  _map_0:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_11:any;
  _map_1:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_27:any;
  _map_2:any;
  /*private*/ _expr_28:any;
  _map_3:any;
  /*private*/ _expr_29:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent0,renderType_HeaderComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_headerContent_0 = new import16.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','navmenu navmenu-default navmenu-fixed-left offcanvas');
    this.renderer.setElementAttribute(this._el_0,'id','mobile-nav');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','navmenu-brand');
    this._text_4 = this.renderer.createText(this._el_3,'Categories\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'span',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','ico-arrow');
    this.renderer.setElementAttribute(this._el_5,'data-target','#mobile-nav');
    this.renderer.setElementAttribute(this._el_5,'data-toggle','offcanvas');
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'i',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','glyphicon glyphicon-remove');
    this._text_8 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_9 = this.renderer.createText(this._el_3,'\n  ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_11 = new import2.AppElement(11,0,this,this._anchor_11);
    this._TemplateRef_11_5 = new import23.TemplateRef_(this._appEl_11,viewFactory_HeaderComponent1);
    this._NgIf_11_6 = new import17.NgIf(this._appEl_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_13 = new import2.AppElement(13,0,this,this._anchor_13);
    this._TemplateRef_13_5 = new import23.TemplateRef_(this._appEl_13,viewFactory_HeaderComponent2);
    this._NgIf_13_6 = new import17.NgIf(this._appEl_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_15 = new import2.AppElement(15,0,this,this._anchor_15);
    this._TemplateRef_15_5 = new import23.TemplateRef_(this._appEl_15,viewFactory_HeaderComponent4);
    this._NgIf_15_6 = new import17.NgIf(this._appEl_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_17 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_18 = new import2.AppElement(18,(null as any),this,this._anchor_18);
    this._TemplateRef_18_5 = new import23.TemplateRef_(this._appEl_18,viewFactory_HeaderComponent7);
    this._NgIf_18_6 = new import17.NgIf(this._appEl_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_20 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','header cover cvi-header-fixed');
    this._text_21 = this.renderer.createText(this._el_20,'\n  ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_20,(null as any));
    this._appEl_22 = new import2.AppElement(22,20,this,this._anchor_22);
    this._TemplateRef_22_5 = new import23.TemplateRef_(this._appEl_22,viewFactory_HeaderComponent8);
    this._NgIf_22_6 = new import17.NgIf(this._appEl_22.vcRef,this._TemplateRef_22_5);
    this._text_23 = this.renderer.createText(this._el_20,'\n  ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','mid-menu');
    this._text_25 = this.renderer.createText(this._el_24,'\n    ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','contain mob-contain');
    this._text_27 = this.renderer.createText(this._el_26,'\n      ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','logo inline mob-inline pull-left js-header-menu-show');
    this._NgClass_28_3 = new import18.NgClass(this.parentInjector.get(import24.IterableDiffers),this.parentInjector.get(import25.KeyValueDiffers),new import26.ElementRef(this._el_28),this.renderer);
    this._text_29 = this.renderer.createText(this._el_28,'\n        ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'img',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','hide-lg menu-icon header-navbar-toggle navbar-toggle');
    this.renderer.setElementAttribute(this._el_30,'data-canvas','body');
    this.renderer.setElementAttribute(this._el_30,'data-target','.navmenu');
    this.renderer.setElementAttribute(this._el_30,'data-toggle','offcanvas');
    this.renderer.setElementAttribute(this._el_30,'src','../../../../images/menu_icon.png');
    this._text_31 = this.renderer.createText(this._el_28,'\n        ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_28,'a',(null as any));
    this._el_33 = this.renderer.createElement(this._el_32,'img',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','logo-img');
    this.renderer.setElementAttribute(this._el_33,'src','../../../../images/logo.png');
    this._text_34 = this.renderer.createText(this._el_28,'\n        ',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_28,(null as any));
    this._appEl_35 = new import2.AppElement(35,28,this,this._anchor_35);
    this._TemplateRef_35_5 = new import23.TemplateRef_(this._appEl_35,viewFactory_HeaderComponent9);
    this._NgIf_35_6 = new import17.NgIf(this._appEl_35.vcRef,this._TemplateRef_35_5);
    this._text_36 = this.renderer.createText(this._el_28,'\n      ',(null as any));
    this._text_37 = this.renderer.createText(this._el_26,'\n      ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_26,'div',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','search inline pull-left');
    this._NgClass_38_3 = new import18.NgClass(this.parentInjector.get(import24.IterableDiffers),this.parentInjector.get(import25.KeyValueDiffers),new import26.ElementRef(this._el_38),this.renderer);
    this._text_39 = this.renderer.createText(this._el_38,'\n        ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_38,'div',(null as any));
    this.renderer.setElementAttribute(this._el_40,'class','input-group');
    this._text_41 = this.renderer.createText(this._el_40,'\n          ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_40,'input',(null as any));
    this.renderer.setElementAttribute(this._el_42,'aria-describedby','basic-addon2');
    this.renderer.setElementAttribute(this._el_42,'class','form-control main-search-input');
    this.renderer.setElementAttribute(this._el_42,'placeholder','Search for Lehengas, Anarkalis..');
    this.renderer.setElementAttribute(this._el_42,'type','text');
    this._DefaultValueAccessor_42_3 = new import19.DefaultValueAccessor(this.renderer,new import26.ElementRef(this._el_42));
    this._NG_VALUE_ACCESSOR_42_4 = [this._DefaultValueAccessor_42_3];
    this._NgModel_42_5 = new import20.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_42_4);
    this._NgControl_42_6 = this._NgModel_42_5;
    this._NgControlStatus_42_7 = new import21.NgControlStatus(this._NgControl_42_6);
    this._text_43 = this.renderer.createText(this._el_40,'\n          ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_40,'span',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','input-group-addon');
    this.renderer.setElementAttribute(this._el_44,'id','basic-addon2');
    this._text_45 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'span',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','glyphicon glyphicon-search');
    this._text_47 = this.renderer.createText(this._el_44,'\n          ',(null as any));
    this._text_48 = this.renderer.createText(this._el_40,'\n        ',(null as any));
    this._text_49 = this.renderer.createText(this._el_38,'\n      ',(null as any));
    this._text_50 = this.renderer.createText(this._el_26,'\n      ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_26,'div',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','options inline pull-right');
    this._text_52 = this.renderer.createText(this._el_51,'\n        ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_51,'div',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','profile option inline pull-right');
    this.renderer.setElementAttribute(this._el_53,'data-target','#loginModal');
    this.renderer.setElementAttribute(this._el_53,'data-toggle','modal');
    this.renderer.setElementAttribute(this._el_53,'style','display: none !important;');
    this._text_54 = this.renderer.createText(this._el_53,'\n          ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_53,'a',(null as any));
    this.renderer.setElementAttribute(this._el_55,'href','https://secure.craftsvilla.com/buy/login');
    this._text_56 = this.renderer.createText(this._el_55,'\n            ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_55,'img',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','img-responsive pull-left icon');
    this.renderer.setElementAttribute(this._el_57,'src','../../../../images/profile_icon.png');
    this._text_58 = this.renderer.createText(this._el_55,'  ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_55,'span',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','hide-sm');
    this._text_60 = this.renderer.createText(this._el_59,'Sign in',(null as any));
    this._text_61 = this.renderer.createText(this._el_55,'\n          ',(null as any));
    this._text_62 = this.renderer.createText(this._el_53,'\n        ',(null as any));
    this._text_63 = this.renderer.createText(this._el_51,'\n        ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_51,'div',(null as any));
    this.renderer.setElementAttribute(this._el_64,'class','cart option inline pull-right');
    this._text_65 = this.renderer.createText(this._el_64,'\n          ',(null as any));
    this._el_66 = this.renderer.createElement(this._el_64,'a',(null as any));
    this.renderer.setElementAttribute(this._el_66,'href','https://securestaticintl.craftsvilla.com/buy/cart');
    this._text_67 = this.renderer.createText(this._el_66,'\n            ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_66,'img',(null as any));
    this.renderer.setElementAttribute(this._el_68,'class','img-responsive icon');
    this.renderer.setElementAttribute(this._el_68,'src','../../../../images/bag_icon.png');
    this._text_69 = this.renderer.createText(this._el_66,'\n            ',(null as any));
    this._el_70 = this.renderer.createElement(this._el_66,'span',(null as any));
    this.renderer.setElementAttribute(this._el_70,'class','notification-circle');
    this.renderer.setElementAttribute(this._el_70,'id','js-cart-count');
    this._text_71 = this.renderer.createText(this._el_66,'\n          ',(null as any));
    this._text_72 = this.renderer.createText(this._el_64,'\n        ',(null as any));
    this._text_73 = this.renderer.createText(this._el_51,'\n        ',(null as any));
    this._text_74 = this.renderer.createText(this._el_51,'\n      ',(null as any));
    this._text_75 = this.renderer.createText(this._el_26,'\n    ',(null as any));
    this._text_76 = this.renderer.createText(this._el_24,'\n  ',(null as any));
    this._text_77 = this.renderer.createText(this._el_20,'\n',(null as any));
    this._text_78 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_79 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_79,'class','menu-slider-container occupy fixed');
    this._NgClass_79_3 = new import18.NgClass(this.parentInjector.get(import24.IterableDiffers),this.parentInjector.get(import25.KeyValueDiffers),new import26.ElementRef(this._el_79),this.renderer);
    this._NgStyle_79_4 = new import22.NgStyle(this.parentInjector.get(import25.KeyValueDiffers),new import26.ElementRef(this._el_79),this.renderer);
    this._text_80 = this.renderer.createText(this._el_79,'\n  ',(null as any));
    this._el_81 = this.renderer.createElement(this._el_79,'div',(null as any));
    this.renderer.setElementAttribute(this._el_81,'class','menu-overlay-div');
    this._text_82 = this.renderer.createText(this._el_79,'\n  ',(null as any));
    this._el_83 = this.renderer.createElement(this._el_79,'div',(null as any));
    this._appEl_83 = new import2.AppElement(83,79,this,this._el_83);
    this._text_84 = this.renderer.createText(this._el_79,'\n',(null as any));
    this._text_85 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._map_0 = import5.pureProxy1((p0:any):{[key: string]:any} => {
      return {'homepage-logo': p0};
    });
    this._expr_7 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_32,'click',this.eventHandler(this._handle_click_32_0.bind(this)));
    this._expr_9 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_38,'mouseover',this.eventHandler(this._handle_mouseover_38_0.bind(this)));
    this._expr_11 = import8.UNINITIALIZED;
    this._map_1 = import5.pureProxy1((p0:any):{[key: string]:any} => {
      return {'homepage-search': p0};
    });
    this._expr_12 = import8.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_42,'ngModelChange',this.eventHandler(this._handle_ngModelChange_42_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_42,'keyup.enter',this.eventHandler(this._handle_keyup_enter_42_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_42,'input',this.eventHandler(this._handle_input_42_2.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_42,'blur',this.eventHandler(this._handle_blur_42_3.bind(this)));
    this._expr_17 = import8.UNINITIALIZED;
    const subscription_0:any = this._NgModel_42_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_42_0.bind(this)));
    this._expr_18 = import8.UNINITIALIZED;
    this._expr_19 = import8.UNINITIALIZED;
    this._expr_20 = import8.UNINITIALIZED;
    this._expr_21 = import8.UNINITIALIZED;
    this._expr_22 = import8.UNINITIALIZED;
    this._expr_23 = import8.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_44,'click',this.eventHandler(this._handle_click_44_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_51,'mouseover',this.eventHandler(this._handle_mouseover_51_0.bind(this)));
    var disposable_9:Function = this.renderer.listen(this._el_66,'click',this.eventHandler(this._handle_click_66_0.bind(this)));
    this._expr_27 = import8.UNINITIALIZED;
    this._map_2 = import5.pureProxy1((p0:any):{[key: string]:any} => {
      return {'change-slider-top': p0};
    });
    this._expr_28 = import8.UNINITIALIZED;
    this._map_3 = import5.pureProxy1((p0:any):{[key: string]:any} => {
      return {display: p0};
    });
    this._expr_29 = import8.UNINITIALIZED;
    var disposable_10:Function = this.renderer.listen(this._el_81,'mouseover',this.eventHandler(this._handle_mouseover_81_0.bind(this)));
    this._viewQuery_headerContent_0.reset([this._appEl_83.vcRef]);
    this.context.contentContainer = this._viewQuery_headerContent_0.first;
    this.init([],[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._el_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._text_85
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import17.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6; }
    if (((token === import23.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import17.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6; }
    if (((token === import23.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import17.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6; }
    if (((token === import23.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import17.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6; }
    if (((token === import23.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import17.NgIf) && (22 === requestNodeIndex))) { return this._NgIf_22_6; }
    if (((token === import23.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import17.NgIf) && (35 === requestNodeIndex))) { return this._NgIf_35_6; }
    if (((token === import18.NgClass) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._NgClass_28_3; }
    if (((token === import19.DefaultValueAccessor) && (42 === requestNodeIndex))) { return this._DefaultValueAccessor_42_3; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (42 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_42_4; }
    if (((token === import20.NgModel) && (42 === requestNodeIndex))) { return this._NgModel_42_5; }
    if (((token === import28.NgControl) && (42 === requestNodeIndex))) { return this._NgControl_42_6; }
    if (((token === import21.NgControlStatus) && (42 === requestNodeIndex))) { return this._NgControlStatus_42_7; }
    if (((token === import18.NgClass) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._NgClass_38_3; }
    if (((token === import18.NgClass) && ((79 <= requestNodeIndex) && (requestNodeIndex <= 84)))) { return this._NgClass_79_3; }
    if (((token === import22.NgStyle) && ((79 <= requestNodeIndex) && (requestNodeIndex <= 84)))) { return this._NgStyle_79_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    const currVal_1:any = this.context.mobileSelectedCategory;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_11_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:boolean = !this.context.mobileSelectedCategory;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_13_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.mobileSelectedCategory;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_15_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.showProtectionPopup;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_18_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.showTopMenu;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_22_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = 'logo inline mob-inline pull-left js-header-menu-show';
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgClass_28_3.klass = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._map_0(!this.context.showMegaMenuCaret);
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgClass_28_3.ngClass = currVal_7;
      this._expr_7 = currVal_7;
    }
    if (!throwOnChange) { this._NgClass_28_3.ngDoCheck(); }
    const currVal_9:any = this.context.showMegaMenuCaret;
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgIf_35_6.ngIf = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_11:any = 'search inline pull-left';
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgClass_38_3.klass = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._map_1(!this.context.showMegaMenuCaret);
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgClass_38_3.ngClass = currVal_12;
      this._expr_12 = currVal_12;
    }
    if (!throwOnChange) { this._NgClass_38_3.ngDoCheck(); }
    changes = (null as any);
    const currVal_17:any = this.context.queryInput;
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._NgModel_42_5.model = currVal_17;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import8.SimpleChange(this._expr_17,currVal_17);
      this._expr_17 = currVal_17;
    }
    if ((changes !== (null as any))) { this._NgModel_42_5.ngOnChanges(changes); }
    const currVal_27:any = 'menu-slider-container occupy fixed';
    if (import5.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._NgClass_79_3.klass = currVal_27;
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._map_2(!this.context.showTopMenu);
    if (import5.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this._NgClass_79_3.ngClass = currVal_28;
      this._expr_28 = currVal_28;
    }
    if (!throwOnChange) { this._NgClass_79_3.ngDoCheck(); }
    const currVal_29:any = this._map_3(this.context.showBottomMenu);
    if (import5.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this._NgStyle_79_4.ngStyle = currVal_29;
      this._expr_29 = currVal_29;
    }
    if (!throwOnChange) { this._NgStyle_79_4.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_18:any = this._NgControlStatus_42_7.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_42,'ng-untouched',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_42_7.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_42,'ng-touched',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_42_7.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_42,'ng-pristine',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_42_7.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_42,'ng-dirty',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_42_7.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_42,'ng-valid',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_42_7.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_42,'ng-invalid',currVal_23);
      this._expr_23 = currVal_23;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_42_5.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.mobileSelectedCategory = (null as any))) !== false);
    return (true && pd_0);
  }
  private _handle_click_32_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.routeNavigateTo('')) !== false);
    return (true && pd_0);
  }
  private _handle_mouseover_38_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.displayMegaMenu(false)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.queryInput = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_enter_42_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.searchItems()) !== false);
    return (true && pd_0);
  }
  private _handle_input_42_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_42_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_42_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_42_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_44_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.searchItems()) !== false);
    return (true && pd_0);
  }
  private _handle_mouseover_51_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.displayMegaMenu(false)) !== false);
    return (true && pd_0);
  }
  private _handle_click_66_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.topCartTracker()) !== false);
    return (true && pd_0);
  }
  private _handle_mouseover_81_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.displayMegaMenu(false)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HeaderComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.HeaderComponent> {
  if ((renderType_HeaderComponent === (null as any))) { (renderType_HeaderComponent = viewUtils.createRenderComponentType('/home/craftsvilla/angular2-aot-webpack2-rollup/app/shared/widgets/header/header.component.html',0,import13.ViewEncapsulation.Emulated,styles_HeaderComponent,{})); }
  return new _View_HeaderComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent1,renderType_HeaderComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'a',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','selected-menu-title');
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'span',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','ico-arrow-back');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'i',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','glyphicon glyphicon-arrow-left');
    this._text_5 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import5.interpolate(1,'\n      ',this.parent.context.mobileSelectedCategory.name,'\n  ');
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_6,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.resetNavView($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeaderComponent1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _TemplateRef_3_5:any;
  _NgFor_3_6:import29.NgFor;
  _text_4:any;
  _text_5:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent2,renderType_HeaderComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_3 = new import2.AppElement(3,0,this,this._anchor_3);
    this._TemplateRef_3_5 = new import23.TemplateRef_(this._appEl_3,viewFactory_HeaderComponent3);
    this._NgFor_3_6 = new import29.NgFor(this._appEl_3.vcRef,this._TemplateRef_3_5,this.parent.parentInjector.get(import24.IterableDiffers),this.parent.ref);
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._text_5
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import29.NgFor) && (3 === requestNodeIndex))) { return this._NgFor_3_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.menuCategoriesData;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_3_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_3_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_3_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HeaderComponent2(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent3,renderType_HeaderComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','dropdown nav navmenu-nav mobile-nav');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','dropdown-toggle');
    this.renderer.setElementAttribute(this._el_2,'data-toggle','dropdown');
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'span',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','ico-arrow');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'i',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','glyphicon glyphicon-chevron-right');
    this._text_7 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import5.interpolate(1,'\n           ',this.context.$implicit.name,'\n          ');
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_3,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.parent.context.mobileSelectedCategory = this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeaderComponent3(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import29.NgFor;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent4,renderType_HeaderComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import23.TemplateRef_(this._appEl_2,viewFactory_HeaderComponent5);
    this._NgFor_2_6 = new import29.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import24.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import29.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.mobileSelectedCategory.data;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_2_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HeaderComponent4(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _TemplateRef_14_5:any;
  _NgFor_14_6:import29.NgFor;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent5,renderType_HeaderComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ul',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','nav navmenu-nav');
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'li',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','dropdown mobile-nav');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'a',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','dropdown-toggle');
    this.renderer.setElementAttribute(this._el_4,'data-toggle','dropdown');
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'span',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','ico-arrow');
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'i',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','glyphicon glyphicon-plus');
    this._text_9 = this.renderer.createText(this._el_6,'\n          ',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_2,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','navmenu-nav dropdown-menu');
    this._text_13 = this.renderer.createText(this._el_12,'\n          ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_12,(null as any));
    this._appEl_14 = new import2.AppElement(14,12,this,this._anchor_14);
    this._TemplateRef_14_5 = new import23.TemplateRef_(this._appEl_14,viewFactory_HeaderComponent6);
    this._NgFor_14_6 = new import29.NgFor(this._appEl_14.vcRef,this._TemplateRef_14_5,this.parent.parent.parentInjector.get(import24.IterableDiffers),this.parent.parent.ref);
    this._text_15 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._text_16 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._text_16,
      this._text_17
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import29.NgFor) && (14 === requestNodeIndex))) { return this._NgFor_14_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this.context.$implicit.data;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgFor_14_6.ngForOf = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_14_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_14_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import5.interpolate(1,'\n          ',this.context.$implicit.name,'\n          ');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_5,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HeaderComponent5(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent5(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent6,renderType_HeaderComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','nav-level-3 mobile-nav');
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'data-target','#mobile-nav');
    this.renderer.setElementAttribute(this._el_2,'data-toggle','offcanvas');
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import5.interpolate(1,'\n              ',this.context.$implicit.name,'\n            ');
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_3,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.routeNavigateTo(this.context.$implicit.href)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeaderComponent6(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent6(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _Tabs_7_4:import30.Tabs;
  _query_Tab_7_0:import16.QueryList<any>;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Tab_9_4:import31.Tab;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _Tab_30_4:import31.Tab;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent7,renderType_HeaderComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','buyer-popup-overlay');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','buyer-protection-popup');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','close-buyer-popup pull-right');
    this._text_5 = this.renderer.createText(this._el_4,'X',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_2,'tabs',(null as any));
    this._appEl_7 = new import2.AppElement(7,2,this,this._el_7);
    var compView_7:any = import32.viewFactory_Tabs0(this.viewUtils,this.injector(7),this._appEl_7);
    this._Tabs_7_4 = new import30.Tabs();
    this._query_Tab_7_0 = new import16.QueryList<any>();
    this._appEl_7.initComponent(this._Tabs_7_4,[],compView_7);
    this._text_8 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'tab',(null as any));
    this._appEl_9 = new import2.AppElement(9,7,this,this._el_9);
    var compView_9:any = import33.viewFactory_Tab0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Tab_9_4 = new import31.Tab();
    this._appEl_9.initComponent(this._Tab_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'b',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Easy Return:',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n          We have a 100% Buyer protection policy wherein you can return the product for any reason whatsoever.\n          You can ship it back to us within 7 days and get a full refund\n        ',(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'b',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Return Process:',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n          Just email us your complaint with order number within 7 days of receipt of the product.\n          You can also login to your account and raise a dispute from there.\n          We will pickup up the product from your doorstep if the pincode is serviceable.\n          In case we can’t pickup, our team will reply to you with an email, containing instructions and return shipping address to which you need to send back the product within 10 days.\n        ',(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'b',(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Refund:',(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n          If you wish, we can offer you a redeemable voucher worth the refund amount for future purchases.\n          Else we can also refund the entire amount back to your bank account without any deductions along.\n        ',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_9.create(this._Tab_9_4,[[].concat([
        this._text_10,
        this._el_11,
        this._text_13,
        this._el_14,
        this._text_16,
        this._el_17,
        this._text_19,
        this._el_20,
        this._text_22,
        this._el_23,
        this._text_25,
        this._el_26,
        this._text_28
      ]
    )],(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'tab',(null as any));
    this.renderer.setElementAttribute(this._el_30,'tabTitle','100% Secure Payments');
    this._appEl_30 = new import2.AppElement(30,7,this,this._el_30);
    var compView_30:any = import33.viewFactory_Tab0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Tab_30_4 = new import31.Tab();
    this._appEl_30.initComponent(this._Tab_30_4,[],compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'b',(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'Payment Modes:',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n          Net Banking, Debit cards/ Credit Cards (Visa, MasterCard, American Express, Diners Club cards accepted)\n        ',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'International Credit Cards',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'b',(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Payment Details:',(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'\n          Immediately after you make a purchase, an invoice with your payment details and a unique payment ID will be sent to you.\n          In case of any issues, our customer care would be happy to help you.\n        ',(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_47 = this.renderer.createElement((null as any),'b',(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'Payment Security:',(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_50 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n          You pay through our secured Payment Gateway and all data is transferred through high level encryption technology.\n          We guarantee your payments are 100% safe with us and the details are never shared with anyone during the payment process.\n        ',(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_30.create(this._Tab_30_4,[[].concat([
        this._text_31,
        this._el_32,
        this._text_34,
        this._el_35,
        this._text_37,
        this._el_38,
        this._text_40,
        this._el_41,
        this._text_43,
        this._el_44,
        this._text_46,
        this._el_47,
        this._text_49,
        this._el_50,
        this._text_52
      ]
    )],(null as any));
    this._text_53 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_7.create(this._Tabs_7_4,[[].concat([
        this._text_8,
        this._el_9,
        this._text_29,
        this._el_30,
        this._text_53
      ]
    )],(null as any));
    this._text_54 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_55 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import31.Tab) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Tab_9_4; }
    if (((token === import31.Tab) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Tab_30_4; }
    if (((token === import30.Tabs) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Tabs_7_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.parent.context.tabsWidgetClass;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Tabs_7_4.widgetClass = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = 'Easy Refunds and Returns';
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Tab_9_4.title = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = '100% Secure Payments';
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Tab_30_4.title = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Tab_7_0.dirty) {
        this._query_Tab_7_0.reset([
          this._Tab_9_4,
          this._Tab_30_4
        ]
        );
        this._Tabs_7_4.tabs = this._query_Tab_7_0;
        this._query_Tab_7_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Tabs_7_4.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.showProtectionPopup = false)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeaderComponent7(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent7(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _el_25:any;
  _RouterLinkWithHref_25_3:import34.RouterLinkWithHref;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent8,renderType_HeaderComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','top-menu hide-sm');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','contain');
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'span',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','pull-left');
    this._text_5 = this.renderer.createText(this._el_4,'India\'s Largest Ethnic Destination. Now Shipping Globally.',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_2,'span',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','pull-right');
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','top-menu-item buyer-protection');
    this._text_10 = this.renderer.createText(this._el_9,'\n          ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'a',(null as any));
    this._el_12 = this.renderer.createElement(this._el_11,'img',(null as any));
    this.renderer.setElementAttribute(this._el_12,'src','../../../../images/shield_icon.png');
    this._text_13 = this.renderer.createText(this._el_11,' 100% Buyer Protection',(null as any));
    this._text_14 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_15 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','top-menu-item');
    this._text_17 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'a',(null as any));
    this.renderer.setElementAttribute(this._el_18,'href','tel:+18002451549');
    this._text_19 = this.renderer.createText(this._el_18,'\n          ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'i',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','glyphicon glyphicon-phone header-phone');
    this._text_21 = this.renderer.createText(this._el_18,'1-800-245-1549\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_16,'\n      ',(null as any));
    this._text_23 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','top-menu-item');
    this._el_25 = this.renderer.createElement(this._el_24,'a',(null as any));
    this.renderer.setElementAttribute(this._el_25,'routerLink','order_tracking');
    this._RouterLinkWithHref_25_3 = new import34.RouterLinkWithHref(this.parent.parentInjector.get(import12.Router),this.parent.parentInjector.get(import35.ActivatedRoute),this.parent.parentInjector.get(import36.LocationStrategy));
    this._text_26 = this.renderer.createText(this._el_25,'Track Order',(null as any));
    this._text_27 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','top-menu-item');
    this._text_29 = this.renderer.createText(this._el_28,'\n        ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'div',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','dropdown inline');
    this._text_31 = this.renderer.createText(this._el_30,'\n          ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'img',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','flag');
    this.renderer.setElementAttribute(this._el_32,'src','../../../../images/usa-flag.gif');
    this._text_33 = this.renderer.createText(this._el_30,' USD\n        ',(null as any));
    this._text_34 = this.renderer.createText(this._el_28,'\n      ',(null as any));
    this._text_35 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','top-menu-item');
    this.renderer.setElementAttribute(this._el_36,'style','cursor: pointer;');
    this._text_37 = this.renderer.createText(this._el_36,'\n        Visit Craftsvilla India\n      ',(null as any));
    this._text_38 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_39 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_40 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'mouseover',this.eventHandler(this._handle_mouseover_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_25,'click',this.eventHandler(this._handle_click_25_0.bind(this)));
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_36,'click',this.eventHandler(this._handle_click_36_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.RouterLinkWithHref) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._RouterLinkWithHref_25_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_3:any = 'order_tracking';
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkWithHref_25_3.routerLink = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_25_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._RouterLinkWithHref_25_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_25,'href',this.viewUtils.sanitizer.sanitize(import37.SecurityContext.URL,currVal_4));
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_25_3.ngOnDestroy();
  }
  private _handle_mouseover_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.displayMegaMenu(false)) !== false);
    return (true && pd_0);
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.showProtectionPopup = true)) !== false);
    return (true && pd_0);
  }
  private _handle_click_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_25_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_36_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.clearCookieAndDomestic($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeaderComponent8(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent8(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent9 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent9,renderType_HeaderComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','hide-sm mega-menu-hamburger');
    this._text_1 = this.renderer.createText(this._el_0,'\n        	   ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'span',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','glyphicon glyphicon-menu-hamburger');
    this._text_3 = this.renderer.createText(this._el_0,'\n         ',(null as any));
    this._expr_2 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_0,'mouseover',this.eventHandler(this._handle_mouseover_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'mouseleave',this.eventHandler(this._handle_mouseleave_0_1.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = (this.parent.context.showBottomMenu == 'block');
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_0,'hovered',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_mouseover_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.displayMegaMenu(true,$event)) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.displayMegaMenu(false,$event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeaderComponent9(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent9(viewUtils,parentInjector,declarationEl);
}